services:
  green-list-waste-alpha-api-two:
    build:
      context: .
      target: development
    depends_on:
      floci:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3001
      NODE_ENV: development
      MONGO_URI: mongodb://mongodb:27017/
      SQS_ENDPOINT: http://floci:4566
      SQS_QUEUE: http://floci:4566/000000000000/glw-poc-background-process
    networks:
      - cdp-tenant
    volumes:
      - ./src:/home/node/src:z
      - ./package.json:/home/node/package.json:z
      - ./.env:/home/node/.env:z
